### ISSUE TITLE
Update output 

### ISSUE THREAD

**Issue by DrLeucine** [wells-wood-research/timed-design#97]
We can simplify the output to just 1 file. As suggested we could use the following structure for a yaml file:

```
settings:
  ignore_uncommon: false
  include_pdbs: true
  model_name: TIMED_Charge
  input_file: my_voxels.hdf5  # Name of the input file
  
pdb_entries:
  - id: "1qys"
    chains:
      A:
        positions: 214
        original_sequence: "MKVLYQLLLGLTFLL"  # Example sequence
        predicted_sequence: "MKVLYQLLLGLTFLL"  # Example prediction
        prediction_probabilities:
          - [0.85, 0.72, 0.65, ..., 0.91]  # Prediction row 1
          - [0.78, 0.66, 0.70, ..., 0.89]  # Prediction row 2
      B:
        positions: 215
        original_sequence: "APLKDQQKFLENYK"  # Another example
        predicted_sequence: "APLNDQQKFLENYK"  # Another example prediction
        prediction_probabilities:
          - [0.88, 0.75, 0.64, ..., 0.92]
          - [0.80, 0.70, 0.69, ..., 0.90]
  - id: "1xyz"
    chains:
      A:
        positions: 220
        original_sequence: "FAKESEQUENCE"  # Example sequence
        predicted_sequence: "FAKESEQUENCE"  # Example prediction
        prediction_probabilities:
          - [0.90, 0.85, 0.60, ..., 0.93]
          - [0.87, 0.74, 0.62, ..., 0.94]
```

Also 

we could probably have two fields of probability lists:
 
wt_sequence: "MKVLYQLLLGLTFLL"  # Example sequence
 
probability_wt_residues: [0.2, 0.4, 0.1]
 
predicted_sequence: "MKVLYQLLLGLTFLL"  # Example prediction
 
probability_predicted_residues: [0.8, 0.6, 0.4]
